### ISSUE TITLE
Javascript Injection vulnerability

### ISSUE THREAD

**Issue by nsavill** [koolreport/core#5]
It is possible to perform Javascript Injection using KoolReport.  Displaying a data field containing the value `"><script>alert(1);</script>` in a Table generated the following HTML when the report was rendered:

```
<td rv="&quot;&gt;&lt;script&gt;alert(1);&lt;/script&gt;"  >
--
  | "><script>alert(1);</script>                        </td>

```
So it looks like the `rv` attribute of the `<td>` tag is correctly processed via htmlentities(), but the actual value of the cell is not.  This results in the Javascript being executed when the report is rendered.

**Comment by koolreport** [comment]
That's correct. Actually we intend to do so for 3 reasons:

1. So that we can insert another widget inside cell of table like Sparkline chart which required js to run.
2. This issue is always overcomed by encrypting string before inserting to database.
3. You can encrypted the string value by using "formatValue" anonymous function.
